### ISSUE TITLE
Long Camel-Case keys are being converted to .-notated keys and breaks

### ISSUE THREAD

**Issue by hgeldenhuys** [loopbackio/loopback-connector-mongodb#611]
## Steps to reproduce

Save a document with init-case. For example: {"projectControllerCreate": {"newProjectInput": {}}}

## Current Behavior

When saving a document that has camel-case gets converted to a .-notation key for some reason.

**projectControllerCreate** becomes **ProjectController.create** and the following error is reported:
```Request PATCH ${URI} failed with status code 500. Error: key ProjectController.create must not contain '.'```

## Expected Behavior

Keys should not be translated

## Additional information

```json
{
  "errors": [
    {
      "message": "Could not invoke operation PATCH /component-documents/{id}",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "componentDocumentControllerUpdateById"
      ],
      "extensions": {
        "method": "patch",
        "path": "/component-documents/{id}",
        "statusCode": 500,
        "responseHeaders": {
          "x-powered-by": "Express",
          "x-content-type-options": "nosniff",
          "content-type": "application/json; charset=utf-8",
          "date": "Mon, 11 Jan 2021 14:24:07 GMT",
          "connection": "close",
          "content-length": "62"
        },
        "responseBody": {
          "error": {
            "statusCode": 500,
            "message": "Internal Server Error"
          }
        }
      }
    }
  ],
  "data": {
    "componentDocumentControllerUpdateById": null
  }
}
```

```shell
Request PATCH /component-documents/acme-corp-test2?publish=patch failed with status code 500. Error: key ProjectController.create must not contain '.'
    at serializeInto (/Users/User/GitHub/api-server/node_modules/mongodb/node_modules/bson/lib/bson/parser/serializer.js:913:19)
    at serializeObject (/Users/User/GitHub/api-server/node_modules/mongodb/node_modules/bson/lib/bson/parser/serializer.js:347:18)
    at serializeInto (/Users/User/GitHub/api-server/node_modules/mongodb/node_modules/bson/lib/bson/parser/serializer.js:937:17)
    at serializeObject (/Users/User/GitHub/api-server/node_modules/mongodb/node_modules/bson/lib/bson/parser/serializer.js:347:18)
    at serializeInto (/Users/User/GitHub/api-server/node_modules/mongodb/node_modules/bson/lib/bson/parser/serializer.js:727:17)
    at serializeObject (/Users/User/GitHub/api-server/node_modules/mongodb/node_modules/bson/lib/bson/parser/serializer.js:347:18)
    at serializeInto (/Users/User/GitHub/api-server/node_modules/mongodb/node_modules/bson/lib/bson/parser/serializer.js:937:17)
    at BSON.serialize (/Users/User/GitHub/api-server/node_modules/mongodb/node_modules/bson/lib/bson/bson.js:64:28)
    at Msg.serializeBson (/Users/User/GitHub/api-server/node_modules/mongodb/lib/core/connection/msg.js:126:22)
    at Msg.makeDocumentSegment (/Users/User/GitHub/api-server/node_modules/mongodb/lib/core/connection/msg.js:118:33)
    at Msg.toBin (/Users/User/GitHub/api-server/node_modules/mongodb/lib/core/connection/msg.js:104:25)
    at MessageStream.writeCommand (/Users/User/GitHub/api-server/node_modules/mongodb/lib/cmap/message_stream.js:55:28)
    at Connection.write (/Users/User/GitHub/api-server/node_modules/mongodb/lib/cmap/connection.js:361:26)
    at _command (/Users/User/GitHub/api-server/node_modules/mongodb/lib/core/wireprotocol/command.js:128:10)
    at command (/Users/User/GitHub/api-server/node_modules/mongodb/lib/core/wireprotocol/command.js:28:5)
    at writeCommand (/Users/User/GitHub/api-server/node_modules/mongodb/lib/core/wireprotocol/write_command.js:47:3)

```

## Related Issues

Only found bson issues where the key was specified with .notation, but in my case I'm using camal-case, so must be the driver that does the translation

**Comment by agnes512** [comment]
@hgeldenhuys Do you mind sharing your model? I just tested with a simple model with some camel case prop names. It works fine with POST, PATCH, GET, etc. requests. I am using `"loopback-connector-mongodb": "^5.5.0",` It would be good if you could provide more information. Thank you.
